# Generated by Django 4.2.5 on 2023-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_article_image_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_image",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="news/"
            ),
        ),
    ]
