# Generated by Django 4.2.5 on 2023-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0006_alter_article_options_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/",
                verbose_name="Makaleye Fotoğraf Ekleyin",
            ),
        ),
    ]
